-- Simple business additions - assumes categories and villages already exist
-- This script just adds sample businesses to your existing data

INSERT INTO businesses (
    name, slug, description, category_id, village_id, 
    phone, email, website, address, price_range, 
    verified, featured, tags, features, languages, season
) VALUES 
(
    'Artemon Pottery Workshop',
    'artemon-pottery-workshop',
    'Traditional pottery workshop creating authentic Sifnian ceramics using local clay and time-honored techniques.',
    (SELECT id FROM categories WHERE name = 'Pottery & Crafts' LIMIT 1),
    (SELECT id FROM villages WHERE name = 'Artemonas' LIMIT 1),
    '+30 22840 31245',
    'info@artemonpottery.gr',
    'https://artemonpottery.gr',
    'Main Street, Artemonas, Sifnos 84003',
    '€€',
    true,
    true,
    ARRAY['Traditional', 'Handmade', 'Local Clay'],
    ARRAY['Pottery Classes', 'Custom Orders', 'Shipping Available'],
    ARRAY['Greek', 'English'],
    'Year Round'
),
(
    'Omega3 Traditional Taverna',
    'omega3-traditional-taverna',
    'Seaside taverna serving fresh seafood and traditional Sifnian specialties with stunning sunset views.',
    (SELECT id FROM categories WHERE name = 'Food & Drink' LIMIT 1),
    (SELECT id FROM villages WHERE name = 'Platis Gialos' LIMIT 1),
    '+30 22840 71234',
    'reservations@omega3sifnos.com',
    'https://omega3sifnos.com',
    'Platis Gialos Beach, Sifnos 84003',
    '€€€',
    true,
    true,
    ARRAY['Seafood', 'Sunset Views', 'Family-run'],
    ARRAY['Sea View', 'Outdoor Seating', 'WiFi', 'Parking'],
    ARRAY['Greek', 'English', 'French'],
    'April - October'
),
(
    'Kastro Traditional Suites',
    'kastro-traditional-suites',
    'Luxury suites in restored medieval houses with panoramic sea views and authentic island architecture.',
    (SELECT id FROM categories WHERE name = 'Accommodation' LIMIT 1),
    (SELECT id FROM villages WHERE name = 'Kastro' LIMIT 1),
    '+30 22840 51678',
    'info@kastrosuites.gr',
    'https://kastrosuites.gr',
    'Medieval Village, Kastro, Sifnos 84003',
    '€€€€',
    true,
    true,
    ARRAY['Luxury', 'Sea View', 'Historic'],
    ARRAY['Sea View', 'Air Conditioning', 'WiFi', 'Breakfast'],
    ARRAY['Greek', 'English', 'German'],
    'April - November'
),
(
    'Sifnos Hiking Adventures',
    'sifnos-hiking-adventures',
    'Guided hiking tours exploring ancient paths, hidden beaches, and traditional villages.',
    (SELECT id FROM categories WHERE name = 'Experiences' LIMIT 1),
    (SELECT id FROM villages WHERE name = 'Apollonia' LIMIT 1),
    '+30 22840 33456',
    'adventures@sifnoshiking.gr',
    'https://sifnoshiking.gr',
    'Central Square, Apollonia, Sifnos 84003',
    '€€',
    true,
    false,
    ARRAY['Hiking', 'Local Guide', 'Small Groups'],
    ARRAY['Professional Guide', 'Equipment Provided', 'Photography Tips'],
    ARRAY['Greek', 'English'],
    'March - November'
),
(
    'Kamares Beach Hotel',
    'kamares-beach-hotel',
    'Family-run hotel directly on Kamares beach offering comfortable rooms with sea views.',
    (SELECT id FROM categories WHERE name = 'Accommodation' LIMIT 1),
    (SELECT id FROM villages WHERE name = 'Kamares' LIMIT 1),
    '+30 22840 31890',
    'info@kamaresbeachhotel.gr',
    'https://kamaresbeachhotel.gr',
    'Kamares Beach, Sifnos 84003',
    '€€',
    true,
    false,
    ARRAY['Beach Front', 'Family Friendly', 'Traditional'],
    ARRAY['Beach Access', 'Sea View', 'WiFi', 'Breakfast'],
    ARRAY['Greek', 'English'],
    'April - October'
);
