// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://entbcjcrmvjrnjqbniqc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVudGJjamNybXZqcm5qcWJuaXFjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgxOTMwNDgsImV4cCI6MjA3Mzc2OTA0OH0.PFXv3h3boR8yfD9lAJmyt97HT7mWI8msoWMeypSg7ww";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});